language: perl
perl:
  - '5.24'
  - '5.22'
distro: trusty
sudo: required
cache:
  directories:
    - perl_modules
before_install:
  #  Disable Gtk stuff for speed reasons
  #  Reinstate when we add the GUI variant
  #  NO - leave in until issue #581 is finalised
  #  as it has GUI deps
  - sudo apt-get install libgnomecanvas2-dev

  # Here as well as cpanfile because of dependency problems if not installed before Gnome2::Canvas
  - cpanm --notest ExtUtils::Depends ExtUtils::PkgConfig Glib Gtk2

  # Here as well as cpanfile because -v stops travis from timing out and killing the build
  # (and -v for the whole install produces a ridiculously large log)
  #  Could adapt approach used in https://github.com/shawnlaffan/bd_travis_experiment
  #  or install libgdal-dev via apt-get (if it can be located)
  - cpanm -v Geo::GDAL
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  
  #  Let's see if we can find where libgdal went.
  #  It should be in ./gdal
  - find . -name 'libgdal*' -print
env:
  - BD_NO_TEST_GUI=1
script: prove -l -j4
# blocklist
branches:
  except:
  - ppm
  #  list GUI only branches here since we lack GUI tests
  - issue_630_export_user_tree_colours
  - issue_633_remove_pixbuf

cache:
  directories:
  - $HOME/gdal
