#os:
#  - linux
#  - osx
language: perl
matrix:
  include:
    - os: osx
      env: BD_NO_TEST_GUI=1
      #perl: '5.24'
    #- os: osx
    #  env: BD_NO_TEST_GUI=0
    ##  linux stuff - uncomment before merging
    #- os: linux
    #  perl: '5.24'
    #  env: BD_NO_TEST_GUI=1
    #  dist: trusty
    #  language: perl
    #- os: linux
    #  perl: '5.24'
    #  env: BD_NO_TEST_GUI=0
    #  dist: trusty
    #  language: perl
    #- os: linux
    #  perl: '5.22'
    #  env: BD_NO_TEST_GUI=1
    #  dist: trusty
    #  language: perl
sudo: required
cache:
  directories:
    #  homebrew files
    - /usr/local
    - perl_modules
#    - gdal_builds

before_install:
  #  homebrew
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew install perl
  - brew install cpanminus
  #- brew install gtk+
  #- brew install pango
  #  dirty hack to ensure we get the brewed perl
  - export PATH=/usr/local/bin:${PATH}
  
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  #- cpanm Pango Gtk2 Gnome2::Canvas IO::Socket::SSL PAR::Packer
  - cpanm Task::Biodiverse::NoGUI
  #- cpanm Task::Biodiverse
  #- cpanm Task::Biodiverse::NoGUI
  
  - brew tap homebrew/boneyard
  - brew tap osgeo/osgeo4mac
  #- echo Installing GDAL
  - brew install --verbose https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/master/boneyard/gdal-20.rb
  #- echo Done GDAL
  #- brew install gdk-pixbuf pango gtk+ libgnomecanvas
  #- brew install gtk+3 libglade 
  - export PERL_GDAL_CONFIG=/usr/local/bin/gdal-config
  
  #  biodiverse deps
  
  - cpanm  --force Geo::GDAL
    
  #  should not be needed
  #- cpanm Gtk3 Gtk2::GladeXML Glib::Object::Introspection
    
  
  #  linux stuff - uncomment before merging
  ##  local::lib target is cached
  #- cpanm --notest local::lib
  #- eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  #
  ##  just to be sure 
  #- find . -name "build_gdal_travis.sh" -print
  ##- echo ${PWD}
  #
  ##  call the gdal build script
  ##- chmod +x ./etc/build_gdal_travis.sh
  #- sh ./etc/build_gdal_travis.sh
  #
  ##  Disable Gtk stuff for speed reasons
  ##  Reinstate when we add the GUI variant
  #- if [ "$BD_NO_TEST_GUI" = 0 ]; then sudo apt-get install libgnomecanvas2-dev; fi;
  #
  ## Here as well as cpanfile because of dependency problems if not installed before Gnome2::Canvas
  #- if [ "$BD_NO_TEST_GUI" = 0 ]; then cpanm --notest ExtUtils::Depends ExtUtils::PkgConfig Glib Gtk2; fi;
  #
  #- if [ "$BD_NO_TEST_GUI" = 0 ]; then cpanm --quiet --installdeps --notest --with-all-features .; fi;


script: prove -l -j4
# blocklist
branches:
  except:
    - ppm
