language: perl
perl:
  - '5.24'
  - '5.22'
distro: trusty
sudo: required
cache:
  directories:
    - perl_modules
    - $HOME/gdal
env:
  - gdal_version=2.1.3
  - geo_gdal_tar=Geo-GDAL-2.010301.tar.gz
  - geo_gdal_dir=Geo-GDAL-2.010301
before_install:

  #  build a gdal
  - export gdal_home=$HOME/gdal/${gdal_version}
  - mkdir -p ${gdal_home}
  - export PATH=${gdal_home}/bin:$PATH
  - gdalconfig=`find $gdal_home -name gdal-config -print`
  - echo $gdalconfig
  - echo http://download.osgeo.org/gdal/${gdal_version}/gdal-${gdal_version}.tar.gz
  - if [ -n $gdalconfig ]; then wget http://download.osgeo.org/gdal/${gdal_version}/gdal-${gdal_version}.tar.gz; fi
  - if [ -n $gdalconfig ]; then tar -xzvf gdal-${gdal_version}.tar.gz; fi
  - if [ -n $gdalconfig ]; then cd gdal-${gdal_version} && ./configure --prefix=$HOME/gdal/${gdal_version} && make && make install; fi
  - if [ -n $gdalconfig ]; then cd ${startdir}; fi
  - if [ -n $gdalconfig ]; then gdalconfig=`which gdal-config`; fi

  # Here as well as cpanfile because -v stops travis from timing out and killing the build
  # (and -v for the whole install produces a ridiculously large log)
  #  Could adapt approach used in https://github.com/shawnlaffan/bd_travis_experiment
  #  or install libgdal-dev via apt-get (if it can be located)
  - cpanm -v Geo::GDAL --gdal-config=$gdal_config

  #  Disable Gtk stuff for speed reasons
  #  Reinstate when we add the GUI variant
  #  NO - leave in until issue #581 is finalised
  #  as it has GUI deps
  - sudo apt-get install libgnomecanvas2-dev

  # Here as well as cpanfile because of dependency problems if not installed before Gnome2::Canvas
  - cpanm --notest ExtUtils::Depends ExtUtils::PkgConfig Glib Gtk2

  #  Let's see if we can find where gdal-config went.
  #  It should be in ./gdal
  - find . $HOME $TRAVIS_BUILD -name 'gdal*' -print
  
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  
env:
  - BD_NO_TEST_GUI=1
script: prove -l -j4
# blocklist
branches:
  except:
  - ppm
  #  list GUI only branches here since we lack GUI tests
  - issue_630_export_user_tree_colours
  - issue_633_remove_pixbuf
