branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.24.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - set BDV_PPM=https://raw.githubusercontent.com/shawnlaffan/biodiverse/master/etc/ppm/ppm524_x64
  - set have_geo_gdal=0
  - FOR /F "delims=" %%i IN ('perl -MGeo::GDAL -e"print 1"') DO set have_geo_gdal=1
  - IF "%have_geo_gdal%"=="0" ppm install %BDV_PPM%/Geo-GDAL.ppd
  
  - cpanm --notest Task::Biodiverse::NoGUI
  - cpanm --notest List::MoreUtils~0.425
  - cpanm --notest List::Unique::DeterministicOrder
  #  make sure something goes to screen for Alien::gdal to avoid timeouts
  - cpanm -v Geo::GDAL::FFI | perl -ne "BEGIN {$|=1; open our $log, q{>}, q{build.log}}; print qq{\n} if 0 == ($. % 90); print q{.}; print {$log} $_;" || type build.log
  #- cpanm --installdeps --notest --with-all-features .


build_script:
  - set BD_NO_TEST_GUI=1
  - prove -l

