branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl -version 5.24.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - set BDV_PPM=https://github.com/shawnlaffan/biodiverse/raw/ppm/ppm524_x64
  - ppm install %BDV_PPM%/Geo-GDAL.ppd
  #- cpanm --installdeps --notest  .
  - cpanm --notest Task::Biodiverse::NoGUI


build_script:
  - set BD_NO_TEST_GUI=1
  - prove -l

